#!/bin/bash
#echo privet $1
# увеличивает версию, последнюю цифру abcx.x.x.xx
versionInc() {
IFS='.' read -ra verArr <<< "$1"  # разбор строки

function join_by { local IFS="$1"; shift; echo "$*"; } # объединим массив
count=${#verArr[@]}			# Всего в массиве
lastc=$((count-1))			# последний элемент
mag=$((verArr[lastc]+1))	# прибавим 1
verArr[lastc]=$mag			# вернем в массив
itog=$(join_by . "${verArr[@]}") # объединяем массив через точку
echo "$itog"
}

#versionInc $1

gitSave(){
    git status --short;
	local tag=`git describe --tags | cut -d "-" -f 1`;
	echo Отправляем изменения на сервр, последний тэг: $tag; 
    local newtag=$(versionInc "$tag")
	read -p "Введите комментарий [ n-отменить отправку ( по умолчанию: $newtag )]: " commitname;
	local comment=${commitname:-$newtag};
	if [[ $comment == "n" ]];
	then
	echo вы отказались отправлять изменения;
	exit 0;
	else
    git add .
	git commit -a -m $comment ;
	git push origin;
#	git push origin --tags ;
	echo end;
	fi;
	createNewTag "$newtag"
}

createNewTag(){
#set -e ;
#	line=`git describe --tags | cut -d "-" -f 1`;
#	echo $$line; 
	local newtag=$1
	echo Введите новый tag : $newtag [n - отмена];
	read line;
	if [[ $newtag == "n" ]]; 
	then 
	echo вы отказались;
	exit 7;
	else
	git tag $newtag ;
	git push origin --tags ;
	echo end;
	fi;
}

gitSave